/*
  Local-only hackathon prototype: progress is saved in localStorage so a
  timeout or reload does not discard fictional renewal data. No data is sent
  anywhere and no document contents are retained.
*/
const STORAGE_KEY = "renewalPathPrototype_v2";
const app = document.querySelector("#app");
const EMPTY = {version:2,screen:"lookup",lookup:{dl:"",dob:""},recordShown:false,renewalStep:0,form:{address:"",city:"",category:""},otp:"",otpResendAt:0,otpExpiresAt:0,uploaded:"",acknowledgement:"",expectedUpdate:""};
let state = structuredClone(EMPTY);
let storageAvailable = true;
function esc(value) { const node=document.createElement("div"); node.textContent=String(value||""); return node.innerHTML; }
function plain(value) { return value && typeof value==="object" && !Array.isArray(value); }
function load() {
  try {
    const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));
    if (!plain(saved) || saved.version!==2) return;
    state={...structuredClone(EMPTY),...saved,lookup:{...EMPTY.lookup,...(plain(saved.lookup)?saved.lookup:{})},form:{...EMPTY.form,...(plain(saved.form)?saved.form:{})}};
    if (!["lookup","renewal","otp","upload","confirmation","tracker"].includes(state.screen)) state.screen="lookup";
    state.renewalStep=state.renewalStep===1?1:0;
  } catch (_) { storageAvailable=false; }
}
function save() { try { localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); storageAvailable=true; } catch (_) { storageAvailable=false; } }
function reset() { try { localStorage.removeItem(STORAGE_KEY); } catch (_) { storageAvailable=false; } state=structuredClone(EMPTY); render(); }
function go(screen) { state.screen=screen; save(); render(); window.scrollTo({top:0,behavior:"smooth"}); }
function limits() {
  const now=new Date(), min=new Date(now.getFullYear()-110,now.getMonth(),now.getDate()), max=new Date(now.getFullYear()-18,now.getMonth(),now.getDate());
  const iso=(date)=>date.toISOString().slice(0,10);
  return {min:iso(min),max:iso(max),label:max.toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})};
}
function updateDate() { return new Date(Date.now()+432000000).toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"}); }
function summary(errors) { return errors.length ? '<div class="error-summary" role="alert" tabindex="-1"><h2>Please correct the following</h2><ul>'+errors.map((e)=>'<li><a href="#'+e.id+'">'+esc(e.text)+'</a></li>').join("")+'</ul></div>' : ""; }
function saved() { return storageAvailable ? '<p class="saved" role="status">Saved on this device</p>' : '<p class="helper" role="status">Your browser is blocking local saving. Keep this tab open while you complete the demo.</p>'; }
function render() { const views={lookup,renewal,otp,upload,confirmation,tracker}; app.innerHTML=views[state.screen](); bind(); }
function lookup() {
  const date=limits();
  return '<section class="card"><p class="eyebrow">Start a renewal</p><h1>Find your fictional licence record</h1><p class="intro">Use demo details only. Nothing is checked against a real service.</p><form id="lookup-form" novalidate><div id="lookup-errors"></div><div class="field"><label for="dl">Demo licence number</label><input id="dl" name="dl" maxlength="16" autocomplete="off" autocapitalize="characters" value="'+esc(state.lookup.dl)+'" aria-describedby="dl-hint dl-error"><span id="dl-hint" class="hint">Enter 16 letters, numbers, or hyphens. Example: DEMO-2026-A-0001.</span><span class="field-error" id="dl-error"></span></div><div class="field"><label for="dob">Date of birth</label><input id="dob" name="dob" type="date" min="'+date.min+'" max="'+date.max+'" value="'+esc(state.lookup.dob)+'" aria-describedby="dob-hint dob-error"><span id="dob-hint" class="hint">Choose a date from the calendar. This demo is for applicants aged 18 or older, on or before '+date.label+'.</span><span class="field-error" id="dob-error"></span></div><button class="primary" type="submit">Check status</button></form>'+(state.recordShown?'<div class="record" aria-live="polite"><h2>Fictional demo record found</h2><p><strong>Name:</strong> Aanya Rao</p><p><strong>Licence:</strong> DEMO-2026-A-0001</p><p><strong>Expires:</strong> 16 September 2026</p><div class="button-row"><button class="primary" type="button" data-go="renewal">Continue renewal</button></div></div>':"")+'<div class="divider"></div><button class="text-button" type="button" data-go="tracker">Track an existing application</button></section>';
}
function renewal() {
  const first=state.renewalStep===0;
  const fields=first ? '<div class="field"><label for="address">Current address</label><input id="address" name="address" autocomplete="street-address" value="'+esc(state.form.address)+'" aria-describedby="address-error"><span class="field-error" id="address-error"></span></div><div class="field"><label for="city">City or town</label><input id="city" name="city" autocomplete="address-level2" value="'+esc(state.form.city)+'" aria-describedby="city-error"><span class="field-error" id="city-error"></span></div>' : '<fieldset class="field"><legend class="field-label">Licence category to renew</legend><div class="radio-option"><input id="private" type="radio" name="category" value="private" '+(state.form.category==="private"?"checked":"")+"><label for=\"private\">Private vehicle (fictional demo category)</label></div><div class=\"radio-option\"><input id=\"two-wheeler\" type=\"radio\" name=\"category\" value=\"two-wheeler\" "+(state.form.category==="two-wheeler"?"checked":"")+"><label for=\"two-wheeler\">Two-wheeler (fictional demo category)</label></div><span class=\"field-error\" id=\"category-error\"></span></fieldset>";
  return '<section class="card"><p class="eyebrow">Renewal form</p><div class="progress" aria-label="Renewal form progress"><span class="active"></span><span class="'+(!first?"active":"")+'"></span><span></span></div><h1>'+(first?"Confirm your address":"Confirm your category")+'</h1><p class="intro">One small decision at a time. Your completed fields save as you type.</p>'+saved()+'<form id="renewal-form" novalidate><div id="renewal-errors"></div>'+fields+'<div class="button-row '+(first?"":"split")+'">'+(first?"":'<button class="secondary" type="button" data-back>Back</button>')+'<button class="primary" type="submit">'+(first?"Continue":"Send verification code")+'</button></div></form></section>';
}
function otp() {
  const seconds=Math.max(0,Math.ceil((state.otpResendAt-Date.now())/1000));
  let boxes=""; for(let i=0;i<6;i+=1) boxes+='<input inputmode="numeric" pattern="[0-9]*" maxlength="1" autocomplete="one-time-code" aria-label="Digit '+(i+1)+' of 6" data-otp="'+i+'" value="'+esc(state.otp[i]||"")+'">';
  return '<section class="card"><p class="eyebrow">Secure check</p><h1>Enter the demo code</h1><p class="intro">A simulated code was sent to your fictional mobile number. Enter any six digits to continue.</p><form id="otp-form" novalidate><div class="otp-grid" aria-label="Six digit one-time code">'+boxes+'</div><span id="otp-error" class="field-error"></span><p class="timer" id="timer">'+(seconds?"You can resend in "+seconds+"s":"You can request a new code now.")+'</p><button id="resend" class="text-button" type="button" '+(seconds?"disabled":"")+'>Resend code</button><div class="button-row"><button id="otp-continue" class="primary" type="submit">Continue</button></div></form></section>';
}
function upload() { return '<section class="card"><p class="eyebrow">Supporting document</p><h1>Add one document</h1><p class="intro">Choose a JPG, PNG, or PDF smaller than 5MB. It is checked only in this browser and is never uploaded.</p><form id="upload-form" novalidate><div class="upload-zone"><label for="document">Select a document</label><input id="document" type="file" accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf" aria-describedby="file-hint file-restore file-error"><p id="file-hint" class="helper">Accepted: JPG, PNG, or PDF · maximum 5MB</p><p class="helper" id="file-restore" role="status">'+(state.uploaded?'You selected <strong>'+esc(state.uploaded)+'</strong> earlier. Browsers do not keep file selections after a reload or when you return here for security reasons — please choose it again to continue.':"")+'</p><p class="file-name" id="file-name"></p><span class="field-error" id="file-error"></span></div><div class="button-row"><button class="primary" type="submit">Review and submit</button></div></form></section>'; }
function confirmation() { return '<section class="card"><p class="eyebrow">Application received</p><h1>Your renewal request is saved</h1><div class="status-box"><div class="status-icon" aria-hidden="true">✓</div><h2>Application under review</h2><p>Expected update by <strong>'+esc(state.expectedUpdate)+'</strong>.</p><div class="ack">'+esc(state.acknowledgement)+'</div><p class="helper">Save this fictional acknowledgment number to return to this status anytime in this browser.</p></div><div class="button-row"><button class="primary" type="button" data-go="tracker">Track this application</button></div><button class="text-button" type="button" data-new>Clear this demo and start again</button></section>'; }
function tracker() { return '<section class="card"><p class="eyebrow">Status tracker</p><h1>Track a renewal application</h1><p class="intro">Enter the fictional acknowledgment number shown after submission.</p><form id="tracker-form" novalidate><div class="field"><label for="ack">Acknowledgment number</label><input id="ack" name="ack" maxlength="14" autocomplete="off" autocapitalize="characters" placeholder="Example: RP-DEMO-123456" aria-describedby="ack-error"><span class="field-error" id="ack-error"></span></div><button class="primary" type="submit">Check application status</button></form><div id="tracker-result"></div><div class="divider"></div><button class="text-button" type="button" data-go="lookup">Return to start</button></section>'; }
function setError(id,message) { document.querySelector("#"+id)?.setAttribute("aria-invalid","true"); const text=document.querySelector("#"+id+"-error"); if(text) text.textContent=message; }
function clearError(id) { document.querySelector("#"+id)?.removeAttribute("aria-invalid"); const text=document.querySelector("#"+id+"-error"); if(text) text.textContent=""; }
function bind() { document.querySelectorAll("[data-go]").forEach((button)=>button.addEventListener("click",()=>go(button.dataset.go))); document.querySelector("[data-new]")?.addEventListener("click",reset); bindLookup(); bindRenewal(); bindOtp(); bindUpload(); bindTracker(); }
function bindLookup() {
  const form=document.querySelector("#lookup-form"); if(!form) return; const date=limits();
  ["dl","dob"].forEach((id)=>{const input=form.elements[id]; input.addEventListener("input",()=>{state.lookup[id]=id==="dl"?input.value.toUpperCase():input.value; save(); clearError(id);}); if(id==="dob") input.addEventListener("click",()=>{try{input.showPicker?.();}catch(_){}});});
  form.addEventListener("submit",(event)=>{event.preventDefault(); const dl=form.dl.value.trim().toUpperCase(),dob=form.dob.value,errors=[]; if(!/^[A-Z0-9-]{16}$/.test(dl)) errors.push({id:"dl",text:"Enter a 16-character demo licence number using letters, numbers, or hyphens."}); if(!dob) errors.push({id:"dob",text:"Choose your date of birth from the calendar."}); else if(dob<date.min||dob>date.max||Number.isNaN(Date.parse(dob+"T12:00:00"))) errors.push({id:"dob",text:"Choose a date between "+date.min+" and "+date.max+"; this demo is for applicants aged 18 to 110."}); document.querySelector("#lookup-errors").innerHTML=summary(errors); ["dl","dob"].forEach(clearError); if(errors.length){errors.forEach((item)=>setError(item.id,item.text)); document.querySelector(".error-summary").focus(); return;} state.lookup={dl,dob}; state.recordShown=true; save(); render();});
}
function bindRenewal() {
  const form=document.querySelector("#renewal-form"); if(!form) return;
  form.querySelectorAll("input").forEach((input)=>input.addEventListener("input",()=>{state.form[input.name]=input.value; save(); clearError(input.name==="category"?"category":input.name);}));
  document.querySelector("[data-back]")?.addEventListener("click",()=>{state.renewalStep=0;save();render();});
  form.addEventListener("submit",(event)=>{event.preventDefault(); const errors=[]; if(state.renewalStep===0){if(!state.form.address.trim())errors.push({id:"address",text:"Enter your current address."});if(!state.form.city.trim())errors.push({id:"city",text:"Enter your city or town."});}else if(!["private","two-wheeler"].includes(state.form.category))errors.push({id:"category",text:"Choose the licence category you want to renew."}); document.querySelector("#renewal-errors").innerHTML=summary(errors); ["address","city","category"].forEach(clearError); if(errors.length){errors.forEach((item)=>setError(item.id,item.text));document.querySelector(".error-summary").focus();return;} if(state.renewalStep===0){state.renewalStep=1;save();render();return;} state.otp="";state.otpResendAt=Date.now()+30000;state.otpExpiresAt=Date.now()+600000;go("otp");});
}
function bindOtp() {
  const form=document.querySelector("#otp-form"); if(!form)return; const boxes=[...document.querySelectorAll("[data-otp]")],write=()=>{state.otp=boxes.map((box)=>box.value).join("");save();};
  boxes.forEach((box,index)=>{box.addEventListener("input",()=>{box.value=box.value.replace(/\D/g,"").slice(-1);write();if(box.value&&boxes[index+1])boxes[index+1].focus();});box.addEventListener("keydown",(event)=>{if(event.key==="Backspace"&&!box.value&&boxes[index-1])boxes[index-1].focus();});box.addEventListener("paste",(event)=>{const code=event.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);if(!code)return;event.preventDefault();boxes.forEach((item,i)=>{item.value=code[i]||"";});write();boxes[Math.min(code.length,6)-1].focus();});});
  document.querySelector("#resend").addEventListener("click",()=>{state.otp="";state.otpResendAt=Date.now()+30000;state.otpExpiresAt=Date.now()+600000;save();render();});
  form.addEventListener("submit",(event)=>{event.preventDefault();const error=document.querySelector("#otp-error");if(Date.now()>state.otpExpiresAt){error.textContent="This demo code has expired. Request a new code and try again.";return;}if(!/^\d{6}$/.test(state.otp)){error.textContent="Enter all six digits of the demo code.";return;}const button=document.querySelector("#otp-continue");button.disabled=true;button.textContent="Verifying…";window.setTimeout(()=>go("upload"),1300);});
  const tick=()=>{const timer=document.querySelector("#timer"),resend=document.querySelector("#resend");if(!timer||!resend)return;const seconds=Math.max(0,Math.ceil((state.otpResendAt-Date.now())/1000));timer.textContent=seconds?"You can resend in "+seconds+"s":"You can request a new code now.";resend.disabled=seconds>0;if(seconds)window.setTimeout(tick,500);};tick();
}
function validFile(file) { if(!file)return"Choose a supporting document before continuing.";const extension=file.name.split(".").pop().toLowerCase(),extensions=["jpg","jpeg","png","pdf"],types=["image/jpeg","image/png","application/pdf"];if(!extensions.includes(extension)||(file.type&&!types.includes(file.type)))return"Please choose a JPG, PNG, or PDF file.";if(file.size>5242880)return"This file is "+(file.size/1048576).toFixed(1)+"MB — please upload a file under 5MB.";return""; }
function bindUpload() {
  const form=document.querySelector("#upload-form");if(!form)return;const input=document.querySelector("#document"),error=document.querySelector("#file-error"),name=document.querySelector("#file-name");
  input.addEventListener("change",()=>{const message=validFile(input.files[0]);error.textContent=message;state.uploaded="";name.textContent="";if(message)return;state.uploaded=input.files[0].name;name.textContent="✓ "+state.uploaded+" is ready";save();});
  form.addEventListener("submit",(event)=>{event.preventDefault();const message=validFile(input.files[0]);if(message){error.textContent=message;return;}const random=crypto.getRandomValues(new Uint32Array(1))[0]%1000000;state.acknowledgement="RP-DEMO-"+String(random).padStart(6,"0");state.expectedUpdate=updateDate();save();go("confirmation");});
}
function bindTracker() {
  const form=document.querySelector("#tracker-form");if(!form)return;form.ack.addEventListener("input",()=>{form.ack.value=form.ack.value.toUpperCase();clearError("ack");});
  form.addEventListener("submit",(event)=>{event.preventDefault();const value=form.ack.value.trim().toUpperCase(),error=document.querySelector("#ack-error"),result=document.querySelector("#tracker-result");if(!value){error.textContent="Enter your acknowledgment number.";return;}if(value!==state.acknowledgement){error.textContent="We could not find that fictional acknowledgment number on this browser.";result.innerHTML="";return;}error.textContent="";result.innerHTML='<div class="status-box" aria-live="polite"><div class="status-icon" aria-hidden="true">✓</div><h2>Application under review</h2><p>Your fictional renewal application is saved. Expected update by <strong>'+esc(state.expectedUpdate)+'</strong>.</p></div>';});
}
load();
render();
