/*
  Reliability rationale: this prototype keeps renewal progress in localStorage after every change.
  It directly addresses documented 2026 citizen reports of portal timeouts/errors discarding a
  partly completed renewal. It is deliberately fictional and never contacts a government system.
*/
const STORAGE_KEY = 'renewalPathPrototype_v1';
const app = document.querySelector('#app');
let state = { screen: 'lookup', lookup: {}, recordShown: false, renewalStep: 0, form: { address: '', city: '', category: '' }, otp: '', otpEndsAt: 0, uploaded: '', acknowledgement: '' };

function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (saved) state = { ...state, ...saved, form: { ...state.form, ...(saved.form || {}) } }; } catch (_) {} }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function esc(value='') { const d=document.createElement('div'); d.textContent=value; return d.innerHTML; }
function setScreen(screen) { state.screen = screen; save(); render(); window.scrollTo({top:0,behavior:'smooth'}); }
function errorSummary(errors) { return errors.length ? `<div class="error-summary" role="alert" tabindex="-1"><h2>There is a problem</h2><ul>${errors.map(e=>`<li><a href="#${e.id}">${e.text}</a></li>`).join('')}</ul></div>` : ''; }
function render() { const screens = { lookup, renewal, otp, upload, confirmation, tracker }; app.innerHTML = screens[state.screen](); bind(); }

function lookup() { return `<section class="card"><p class="eyebrow">Start a renewal</p><h1>Find your fictional licence record</h1><p class="intro">Use the demo details below. Nothing is checked against a real service.</p><form id="lookup-form" novalidate>${errorSummary([])}<div class="field"><label for="dl">Demo licence number</label><input id="dl" name="dl" maxlength="16" autocomplete="off" value="${esc(state.lookup.dl||'')}" aria-describedby="dl-hint"/><span id="dl-hint" class="hint">Enter exactly 16 letters or numbers, for example DEMO-2026-A-0001.</span><span class="field-error" id="dl-error"></span></div><div class="field"><label for="dob">Date of birth</label><input id="dob" name="dob" type="date" value="${esc(state.lookup.dob||'')}"/><span class="field-error" id="dob-error"></span></div><button class="primary" type="submit">Check status</button></form>${state.recordShown?`<div class="record" aria-live="polite"><h2>Fictional demo record found</h2><p><strong>Name:</strong> Aanya Rao</p><p><strong>Licence:</strong> DEMO-2026-A-0001</p><p><strong>Expires:</strong> 16 September 2026</p><div class="button-row"><button class="primary" type="button" data-go="renewal">Continue renewal</button></div></div>`:''}<div class="divider"></div><button class="text-button" type="button" data-go="tracker">Track an existing application</button></section>`; }
function renewal() { const step = state.renewalStep; const fields = step === 0 ? `<div class="field"><label for="address">Current address</label><input id="address" name="address" autocomplete="street-address" value="${esc(state.form.address)}"/><span class="field-error"></span></div><div class="field"><label for="city">City or town</label><input id="city" name="city" autocomplete="address-level2" value="${esc(state.form.city)}"/><span class="field-error"></span></div>` : `<fieldset class="field"><legend class="field-label">Licence category to renew</legend>${[['private','Private vehicle (fictional demo category)'],['two-wheeler','Two-wheeler (fictional demo category)']].map(([v,t])=>`<div class="radio-option"><input id="${v}" type="radio" name="category" value="${v}" ${state.form.category===v?'checked':''}/><label for="${v}">${t}</label></div>`).join('')}<span class="field-error"></span></fieldset>`; return `<section class="card"><p class="eyebrow">Renewal form</p><div class="progress" aria-label="Renewal form progress"><span class="active"></span><span class="${step===1?'active':''}"></span><span></span></div><h1>${step===0?'Confirm your address':'Confirm your category'}</h1><p class="intro">Small steps mean each part is saved as you go.</p><p class="saved">Saved on this device</p><form id="renewal-form" novalidate><div id="renewal-errors"></div>${fields}<div class="button-row ${step?'split':''}">${step?'<button class="secondary" type="button" data-back-renewal>Back</button>':''}<button class="primary" type="submit">${step===0?'Continue':'Send verification code'}</button></div></form></section>`; }
function otp() { const digits = Array.from({length:6},(_,i)=>`<input inputmode="numeric" pattern="[0-9]*" maxlength="1" aria-label="Digit ${i+1} of 6" data-otp="${i}" value="${esc(state.otp[i]||'')}"/>`).join(''); const left=Math.max(0,Math.ceil((state.otpEndsAt-Date.now())/1000)); return `<section class="card"><p class="eyebrow">Secure check</p><h1>Enter the demo code</h1><p class="intro">We sent a simulated code to your fictional mobile number. Enter any six digits to continue.</p><form id="otp-form" novalidate><div class="otp-grid" aria-label="Six digit one-time code">${digits}</div><span id="otp-error" class="field-error"></span><p class="timer" id="timer">${left>0?`You can resend in ${left}s`:'You can request a new code now.'}</p><button id="resend" class="text-button" type="button" ${left>0?'disabled':''}>Resend code</button><div class="button-row"><button id="otp-continue" class="primary" type="submit">Continue</button></div></form></section>`; }
function upload() { return `<section class="card"><p class="eyebrow">Supporting document</p><h1>Add one document</h1><p class="intro">Choose a JPG, PNG, or PDF under 5MB. It stays on this device and is never uploaded.</p><form id="upload-form" novalidate><div class="upload-zone"><label for="document">Select a document</label><input id="document" type="file" accept=".jpg,.jpeg,.png,.pdf,application/pdf,image/jpeg,image/png"/><p class="helper">Accepted: JPG, PNG, PDF · maximum 5MB</p><p class="file-name" id="file-name">${state.uploaded?`✓ ${esc(state.uploaded)}`:''}</p><span class="field-error" id="file-error"></span></div><div class="button-row"><button class="primary" type="submit">Review and submit</button></div></form></section>`; }
function confirmation() { const expected = new Date(Date.now()+5*864e5).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'}); return `<section class="card"><p class="eyebrow">Application received</p><h1>Your renewal request is saved</h1><div class="status-box"><div class="status-icon" aria-hidden="true">✓</div><h2>Application under review</h2><p>Expected update by <strong>${expected}</strong>.</p><div class="ack">${esc(state.acknowledgement)}</div><p class="helper">Save this fictional acknowledgment number to return to this status anytime on this browser.</p></div><div class="button-row"><button class="primary" type="button" data-go="tracker">Track this application</button></div><button class="text-button" type="button" data-new>Start another demo</button></section>`; }
function tracker() { return `<section class="card"><p class="eyebrow">Status tracker</p><h1>Track a renewal application</h1><p class="intro">Enter the fictional acknowledgment number shown after submission.</p><form id="tracker-form" novalidate><div class="field"><label for="ack">Acknowledgment number</label><input id="ack" name="ack" autocomplete="off" value="" placeholder="Example: RP-DEMO-000000"/><span class="field-error" id="ack-error"></span></div><button class="primary" type="submit">Check application status</button></form><div id="tracker-result"></div><div class="divider"></div><button class="text-button" type="button" data-go="lookup">Return to start</button></section>`; }

function bind() {
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setScreen(b.dataset.go));
 const lf=document.querySelector('#lookup-form'); if(lf) lf.onsubmit=e=>{e.preventDefault(); const dl=lf.dl.value.trim().toUpperCase(), dob=lf.dob.value, errs=[]; if(!/^[A-Z0-9-]{16}$/.test(dl)) errs.push({id:'dl',text:'Enter a 16-character demo licence number.'}); if(!dob) errs.push({id:'dob',text:'Choose your date of birth.'}); if(errs.length){ lf.querySelector('div')?.remove(); lf.insertAdjacentHTML('afterbegin',errorSummary(errs)); errs.forEach(x=>{document.querySelector('#'+x.id).setAttribute('aria-invalid','true');document.querySelector('#'+x.id+'-error').textContent=x.text;}); document.querySelector('.error-summary').focus(); return;} state.lookup={dl,dob};state.recordShown=true;save();render(); };
 const rf=document.querySelector('#renewal-form'); if(rf){ rf.querySelectorAll('input').forEach(i=>i.oninput=()=>{state.form[i.name]=i.value;save();}); document.querySelector('[data-back-renewal]')?.addEventListener('click',()=>{state.renewalStep=0;save();render();}); rf.onsubmit=e=>{e.preventDefault();let errs=[];if(state.renewalStep===0){if(!state.form.address.trim())errs.push({id:'address',text:'Enter your current address.'});if(!state.form.city.trim())errs.push({id:'city',text:'Enter your city or town.'});}else if(!state.form.category)errs.push({id:'private',text:'Choose a licence category to renew.'});if(errs.length){document.querySelector('#renewal-errors').innerHTML=errorSummary(errs); errs.forEach(x=>{const i=document.querySelector('#'+x.id);i?.setAttribute('aria-invalid','true');});document.querySelector('.error-summary').focus();return;} if(state.renewalStep===0){state.renewalStep=1;save();render();}else{state.otp='';state.otpEndsAt=Date.now()+30000;setScreen('otp');}}; }
 const of=document.querySelector('#otp-form'); if(of){ const inputs=[...document.querySelectorAll('[data-otp]')]; inputs.forEach((i,n)=>{i.oninput=()=>{i.value=i.value.replace(/\D/g,'').slice(-1);state.otp=inputs.map(x=>x.value).join('');save();if(i.value&&inputs[n+1])inputs[n+1].focus();};i.onkeydown=e=>{if(e.key==='Backspace'&&!i.value&&inputs[n-1])inputs[n-1].focus();};}); document.querySelector('#resend').onclick=()=>{state.otp='';state.otpEndsAt=Date.now()+30000;save();render();}; of.onsubmit=e=>{e.preventDefault(); if(state.otp.length!==6){document.querySelector('#otp-error').textContent='Enter all six digits of the demo code.';return;}const b=document.querySelector('#otp-continue');b.disabled=true;b.textContent='Verifying…';setTimeout(()=>setScreen('upload'),1300);}; const tick=()=>{const t=document.querySelector('#timer'),b=document.querySelector('#resend');if(!t)return;const l=Math.max(0,Math.ceil((state.otpEndsAt-Date.now())/1000));t.textContent=l?`You can resend in ${l}s`:'You can request a new code now.';b.disabled=l>0;if(l>0)setTimeout(tick,500);};tick(); }
 const uf=document.querySelector('#upload-form'); if(uf){const input=document.querySelector('#document');input.onchange=()=>{const f=input.files[0],er=document.querySelector('#file-error'),n=document.querySelector('#file-name');er.textContent='';state.uploaded='';if(!f)return;const mb=(f.size/1024/1024).toFixed(1),ok=['image/jpeg','image/png','application/pdf'].includes(f.type);if(!ok)er.textContent='Please choose a JPG, PNG, or PDF file.';else if(f.size>5*1024*1024)er.textContent=`This file is ${mb}MB — please upload a file under 5MB.`;else{state.uploaded=f.name;n.textContent=`✓ ${f.name} is ready`;save();}};uf.onsubmit=e=>{e.preventDefault();if(!state.uploaded){document.querySelector('#file-error').textContent='Choose a supporting document before continuing.';return;}state.acknowledgement='RP-DEMO-'+String(Date.now()).slice(-6);save();setScreen('confirmation');}; }
 const tf=document.querySelector('#tracker-form');if(tf)tf.onsubmit=e=>{e.preventDefault();const v=tf.ack.value.trim().toUpperCase(),er=document.querySelector('#ack-error'),out=document.querySelector('#tracker-result');if(!v){er.textContent='Enter your acknowledgment number.';return;}if(v!==state.acknowledgement){er.textContent='We could not find that fictional acknowledgment number on this browser.';out.innerHTML='';return;}er.textContent='';out.innerHTML=`<div class="status-box"><h2>Application under review</h2><p>Your fictional renewal application is saved. Expected update by <strong>${new Date(Date.now()+5*864e5).toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</strong>.</p></div>`;};
 document.querySelector('[data-new]')?.addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);state={screen:'lookup',lookup:{},recordShown:false,renewalStep:0,form:{address:'',city:'',category:''},otp:'',otpEndsAt:0,uploaded:'',acknowledgement:''};render();});
}
load(); render();
